config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  # resources :products, only: [:show]
  # resources :orders, only: [:new, :create]
  resources :images, only: [:create, :destroy]
  resources :orders

  resources :products do
    resources :orders
    collection do
      get 'range'
    end
  end

  get '/products/tag/:name', to: 'products#tag', as: 'tag_products'
  get '/products/category/:name', to: 'products#category', as: 'category_products'
  post '/products/tag', to: 'products#tag', as: 'find_by_tag'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
  has_ancestry
  before_validation do
    self.ancestry = nil if self.ancestry.blank?
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product

  def send_simple_message(order_params, domain)
    email = 'nikita.arar@gmail.com'

    @product = Product.find(order_params[:product_id])

    RestClient.post "https://api:75a2b5fb22bd04ecc9ab87bb81828e39-52cbfb43-4e467699"\
        "@api.mailgun.net/v3/sandboxeb1c0e0ef3404c488fdda4b3dd9530cd.mailgun.org/messages",
        :from => "Mailgun Sandbox <postmaster@sandboxeb1c0e0ef3404c488fdda4b3dd9530cd.mailgun.org>",
        :to => email,
        :subject => "Куплен товар в интернет-магазине",
        :text => "В интернет-магазине куплен товар:
                \nid: " + order_params["product_id"] + "
                \nНазвание: " + @product.title + "
                \nЦена: " + @product.price.to_s + " грн.

                \n\nИнформация о покупателе:
                \nИмя: " + order_params["name"] + "
                \nТелефон: " + order_params["phone"] + "
                \nE-mail: " + order_params["email"] + "
                \nИнформация о доставке: " + order_params['delivery_info'],


        :html => "В интернет-магазине куплен товар:
                <br><b>Название:</b> <a href='" + domain + Rails.application.routes.url_helpers.product_path(@product)+ "'>" + @product.title + "</a>
                <br><b>Цена:</b> " + @product.price.to_s + " грн.

                <hr>
                <b><u>Информация о покупателе:</u></b>
                <br><b>Имя:</b> " + order_params["name"] + "
                <br><b>Телефон:</b> " + order_params["phone"] + "
                <br><b>E-mail:</b> <a href='mailto:" + order_params["email"] + "'>" + order_params["email"] + "</a>
                <br><b>Информация о доставке:</b> " + order_params['delivery_info']
    # You can see a record of this email in your logs: https://app.mailgun.com/app/logs

    # You can send up to 300 emails/day from this sandbox serverv.
    # Next, you should add your own domain so you can send 10,000 emails/month for free.
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :images
  has_many :orders
  accepts_nested_attributes_for :images, allow_destroy: true

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :tags

  self.per_page = 12

  HIDDEN = 1
  ACTIVE = 2

  validates :title, :description, :price, :status, presence: true
  validates :status, inclusion: { in: [HIDDEN, ACTIVE]}

  def self.statuses
    {'Не показывать' => self::HIDDEN , 'Активный' => self::ACTIVE}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @order = @product.orders.build
  end

  def create
    @order = Order.create(order_params)
    # @order.send_simple_message(order_params, request.host)
  end

  def order_params
    params.require(:order).permit(:name, :phone, :email, :delivery_info, :product_id, :tag_list)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :default_page, only: [:index, :tag, :category]

  def index
    @products = Product.where(status: Product::ACTIVE).includes(:images).paginate(:page => params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def tag
    @products = Product.where(status: Product::ACTIVE).tagged_with(params[:name]).paginate(:page => params[:page])
    render "index"
  end

  def category
    @products = Product.where(status: Product::ACTIVE, category: params[:name]).paginate(:page => params[:page])
    render "index"
  end

  def range
    range = ActiveSupport::JSON.decode(params[:prices]).collect {|i| i.to_i}
    @products = Product.where(status: Product::ACTIVE).where(price: range.min..range.max)
    render "index"
  end

  private

  def default_page
    params[:page] = 1 if params[:page].nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def min_price()
    Product.where(status: Product::ACTIVE).minimum(:price)
  end
  def max_price()
    Product.where(status: Product::ACTIVE).maximum(:price)
  end
  def category_list()
    Category.roots()
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'template', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'price-range', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'price_range', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <div class="contactinfo">
              <ul class="nav nav-pills">
                <li><a href=""><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                <li><a href=""><i class="fa fa-envelope"></i> info@domain.com</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="social-icons pull-right">
              <ul class="nav navbar-nav">
                <li><a href=""><i class="fa fa-facebook"></i></a></li>
                <li><a href=""><i class="fa fa-twitter"></i></a></li>
                <li><a href=""><i class="fa fa-linkedin"></i></a></li>
                <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                <li><a href=""><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="header-middle"><!--header-bottom-->
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <%= link_to "Магазин", "/" %>
          </div>
          <div class="col-lg-4">
            <%= form_tag(find_by_tag_path()) do %>
              <div class="input-group">
                <input type="text" name='name' class="input-medium search-query"
                       placeholder="Поиск по тегу">
                <button type="submit" class="btn">Найти</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div><!--/header-bottom-->
  </header><!--/header-->

  <section class='main-section'>
    <div class='container'>
      <div class="row">
        <div class="col-sm-3">
          <div class="left-sidebar">

            <h2>Категори</h2>
            <div class="panel-group category-products"><!--category-productsr-->
              <% category_list().each do |category|  %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <%= link_to category.name, category_products_path(category) %>
                    </h4>
                    <% if category.has_children? %>
                      <% category.children.each do |child| %>
                        <h5 class="panel-title child">
                          <%= link_to child.name, category_products_path(child) %>
                        </h5>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div><!--/category-products-->

            <h2>Тэги</h2>
            <div class="panel-group category-products"><!--category-productsr-->
              <% ActsAsTaggableOn::Tag.most_used(10).each do |tag|  %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <%= link_to tag, tag_products_path(tag.name) %>
                    </h4>
                  </div>
                </div>
              <% end %>
            </div><!--/category-products-->

            <div class="price-range"><!--price-range-->
              <h2>Price Range</h2>
              <div class="well text-center">
                 <input type="text" class="span2" value="" data-slider-min="<%= min_price() %>" data-slider-max="<%= max_price() %>" data-slider-step="10" data-slider-value="[<%= min_price() %>,<%= max_price() %>]" id="sl2" ><br />
                 <b class="pull-left"><%= min_price() %> грн.</b> <b class="pull-right"><%= max_price() %> грн.</b>
              </div>
            </div><!--/price-range-->
          </div>
        </div>
        <div class='col-sm-9'>
          <%= yield %>
        </div>
    </div>
  </section>

  <footer id="footer"><!--Footer-->
    <div class="footer-widget">
      <div class="container">
        <div class="row">
          <div class="col-sm-2">
            <div class="single-widget">
              <h2>Service</h2>
              <ul class="nav nav-pills nav-stacked">
                <li><a href="#">Online Help</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Order Status</a></li>
                <li><a href="#">Change Location</a></li>
                <li><a href="#">FAQ’s</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-2">
            <div class="single-widget">
              <h2>Quock Shop</h2>
              <ul class="nav nav-pills nav-stacked">
                <li><a href="#">T-Shirt</a></li>
                <li><a href="#">Mens</a></li>
                <li><a href="#">Womens</a></li>
                <li><a href="#">Gift Cards</a></li>
                <li><a href="#">Shoes</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-2">
            <div class="single-widget">
              <h2>Policies</h2>
              <ul class="nav nav-pills nav-stacked">
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Privecy Policy</a></li>
                <li><a href="#">Refund Policy</a></li>
                <li><a href="#">Billing System</a></li>
                <li><a href="#">Ticket System</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-2">
            <div class="single-widget">
              <h2>About Shopper</h2>
              <ul class="nav nav-pills nav-stacked">
                <li><a href="#">Company Information</a></li>
                <li><a href="#">Careers</a></li>
                <li><a href="#">Store Location</a></li>
                <li><a href="#">Affillate Program</a></li>
                <li><a href="#">Copyright</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-3 col-sm-offset-1">
            <div class="single-widget">
              <h2>About Shopper</h2>
              <form action="#" class="searchform">
                <input type="text" placeholder="Your email address" />
                <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                <p>Get the most recent updates from <br />our site and be updated your self...</p>
              </form>
            </div>
          </div>

        </div>
      </div>
    </div>

  </footer><!--/Footer-->

  </body>
</html>

app/views/orders/create.html.erb
<p>Спасибо за заказ. Мы свяжемся с вами в ближайшее время</p>

app/views/orders/new.html.erb
<section id="do_action">
  <div class="container">
    <div class="heading">
      <h3>Форма оформления заказа</h3>
      <p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
    </div>
        <div class="chose_area">
        <%= form_for @order,  class: 'user_option' do |form| %>
          <%= form.hidden_field :product_id %>

          <div class="form-group row">
            <%= form.label :name, class: "col-sm-2 col-form-label"   %>
            <div class="col-sm-8">
              <%= form.text_field :name %>
            </div>
          </div>
          <div class="form-group row">
            <%= form.label :email, class: "col-sm-2 col-form-label"   %>
            <div class="col-sm-8">
              <%= form.email_field :email %>
            </div>
          </div>
          <div class="form-group row">
            <%= form.label :phone, class: "col-sm-2 col-form-label"   %>
            <div class="col-sm-8">
              <%= form.telephone_field :phone %>
            </div>
          </div>
          <div class="form-group ">
              <%= form.label :delivery_info %>
              <%= form.text_area :delivery_info, class: "form-control" %>
          </div>

          <%= link_to 'Назад', :back, class: 'btn btn-default update' %>
          <%= form.submit 'Отправить', class: 'btn btn-default check_out' %>
        <% end %>

        </div>
      </div>
    </div>
  </div>
</section><!--/#do_action-->

app/views/products/_product.html.erb
<div class="col-sm-4">
  <div class="product-image-wrapper">
    <div class="single-products">
      <div class="productinfo text-center">
        <% if product.images.present? %>
          <%= image_tag(product.images.first.image.url(:mini)) %>
        <% else %>
          <%= image_tag 'no-photo.png' %>
        <% end %>
        <h2><%= product.price %> грн.</h2>
        <p><%= product.title %></p>
        <%= link_to(product_path(product), :remote => false, class: "btn btn-default add-to-cart") do %>
          <i class='fa fa-shopping-cart'></i>Подробнее
        <% end %>
      </div>
      <div class="product-overlay">
        <div class="overlay-content">
          <h2><%= product.price %> грн.</h2>
          <p><%= product.title %></p>
            <%= link_to(product_path(product), :remote => false, class: "btn btn-default add-to-cart") do %>
              <i class='fa fa-shopping-cart'></i>Подробнее
            <% end %>
        </div>
      </div>
    </div>
    <div class="choose">
      <ul>
        <li>
            <%= link_to(new_product_order_path(product)) do %>
              <i class="fa fa-plus-square"></i>Купить
            <% end %>
        </li>
        <li>
          <% if product.tag_list.present? %>
            <a><i class="fa fa-tags"></i><%= product.tag_list %>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="padding-right">
  <div class="features_items"><!--features_items-->
    <h2 class="title text-center">Товары</h2>
    <div class='row' id='products'>
      <%= render @products %>
      <%= will_paginate @products, :previous_label => 'Назад', :next_label => 'Вперед' %>
    </div><!--id='products'-->
  </div><!--features_items-->
</div>

app/views/products/show.html.erb
<section>
  <div class="padding-right row product-details"><!--product-details-->
    <div class="col-sm-5">
      <div id="product-images">
        <div id="product-big-image" class='tmb tmb-big'>
          <% if @product.images.present? %>
            <% @product.images.each do |image| %>
              <a href="<%= image.image.url() %>" data-lightbox="roadtrip">
                <% if image == @product.images.first %>
                  <%= image_tag(image.image.url(), class: 'img-show active', id: 'img' + image.id.to_s) %>
                <% else %>
                  <%= image_tag(image.image.url(), class: 'img-show', id: 'img' + image.id.to_s) %>
                <% end %>
              </a>
            <% end %>
          <% else %>
            <%= image_tag 'no-photo.png' %>
          <% end %>
        </div>
        <ul id="product-thumbnails" class="thumbnails list-inline" data-hook="">
          <% @product.images.each do |image| %>
            <li class="tmb">
              <%= image_tag(image.image.url(:thumb), data: image.id ) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="product-information"><!--/product-information-->
        <h2><%= @product.title %></h2>
          <span class='price'><%= @product.price %> грн.</span>
            <%= link_to(new_product_order_path(@product), class: "btn btn-fefault cart", type: "button") do %>
             <i class="fa fa-shopping-cart"></i>
               Купить
            <% end %>
            <br>
        <p><b>Описание:</b></p>
        <p><%= @product.description %></p>
        <p>
          <% @product.tag_list.split do |tag| %>
            <i class="fa fa-tags"></i>
              <%= link_to tag, tag_products_path(tag), class: 'taglist-link' %>
            <% end %>
        </p>
      </div><!--/product-information-->
    </div>
  </div>
</section>